Mh/pek 548
navikt/pensjonskalkulator-frontend pull request #1332
Opened 2024-09-23 13:58 UTC by mlp73

Legger til visning av simuleringsdetaljer

2024-09-23 14:02 UTC, espengjostol commented
> @espengjostol kan du bekrefte at disse detaljene kun kommer i dev, men ikke i prod? Jeg har ikke lagt til noe spesiell sjekk på frontend, dvs. at de vil vises på beregningssiden så snart de er med i responsen. Jeg ønsker å forsikre meg at dette ikke vil oppstå i prod.

De kommer også i prod. Jeg har ikke lagt til noen sjekk på backend heller.

2024-09-23 15:09 UTC, espengjostol reviewed
Dette er vel funksjonalitet som bare testere skal bruke.
Er det noe vi bør ha i kalkulatoren?

2024-09-24 08:21 UTC, espengjostol requested changes
Feature-toggle `utvidet-simuleringsresultat` bør brukes.

2024-09-24 11:01 UTC, mlp73 commented
@espengjostol Fint! :) Se siste commit som tar feature-toggle i bruk.

2024-09-24 14:01 UTC, espengjostol requested changes

2024-09-25 08:34 UTC, mlp73 commented on src/state/api/apiSlice.ts
> +      query: () => '/feature/pensjonskalkulator.utvidet-simuleringsresultat',
bra spotted, takk

2024-09-25 10:15 UTC, merged