Redirect av personer født før 1963 i BFF
navikt/pensjonskalkulator-frontend pull request #1629
Opened 2024-12-13 08:39 UTC by bjorngi

2025-01-13 08:55 UTC, bjorngi commented on server/server.ts
> +app.get('*', redirect163Middleware, async (_req: Request, res: Response) => {
Sjekker `redirect163Middleware` før man blir servert kalkulator

2025-01-13 08:57 UTC, bjorngi commented on .nais/deploy-catbox.yml
> +        - application: wonderwalled-idporten # only in dev
Tillater å kunne hente ut idporten token fra https://wonderwalled-idporten.intern.dev.nav.no/api/obo?aud=dev-gcp:pensjonskalkulator:pensjonskalkulator-frontend

2025-01-13 08:59 UTC, bjorngi commented on server/server.ts
> +
Setter opp unleash for BFF

2025-01-13 08:59 UTC, bjorngi commented on server/server.ts
> +  res.sendStatus(200)
Flytter health endepunkter slik at de ikke spammer loggene

2025-01-13 09:02 UTC, bjorngi commented on src/pages/VeilederInput/KalkulatorRedirect.tsx
> +export const KalkulatorRedirect: React.FC<IKalkulatorRedirectProps> = ({
Komponent for å redirigere med `fnr` (trengs for å kunne sende til Del B)

2025-01-13 09:02 UTC, bjorngi commented on src/pages/VeilederInput/VeilederInput.tsx
> +    return <KalkulatorRedirect fnr={veilederBorgerFnr} />
Sende til Del B for veileder

2025-01-13 09:03 UTC, bjorngi commented on src/router/constants.ts
> +  detaljertKalkulator: '/pensjon/kalkulator/redirect/detaljert-kalkulator',
Bruk eget endepunkt i BFF for redirigering til detaljert kalkulator

2025-01-13 09:04 UTC, bjorngi commented on src/router/loaders.tsx
>  // ////////////////////////////////////////
Fjern bruk at feature toggle i kalkulator klient (gjøres i BFF)

2025-01-13 09:07 UTC, bjorngi commented on server/ensureEnv.ts
> +export const ensureEnv = <T extends Record<string, string>>(variables: T) => {
Stopper applikasjonen å starte dersom miljøvariabler mangler i BFF

2025-03-05 19:50 UTC, bjorngi commented on cypress/e2e/pensjon/kalkulator/henvisning.cy.ts
> -
Logikk flyttes til BFF

2025-03-05 19:52 UTC, bjorngi commented on server/server.ts
> +}
Middleware som sjekker om man skal redirigeres til gammel kalkulator

2025-03-05 19:54 UTC, bjorngi commented on src/pages/VeilederInput/AlertDelB.tsx
> +}
Form for å gjøre en interaktiv redirect til gammel kalkulator, må gjennom BFF for å hente ut veileder informasjon fra azure token

2025-03-05 19:55 UTC, bjorngi commented on src/pages/VeilederInput/VeilederInput.tsx
>          <RouterProvider router={router} />
Varsel som vises til veileder, slik at de ikke blir automatisk redirigert

2025-03-05 19:56 UTC, bjorngi commented on src/router/loaders.tsx
> +    return redirect(paths.start)
Trenger ikke 1963 redirect i frontend da det gjøres i BFF, men hopper over LandingPage dersom man er veileder

2025-03-06 11:16 UTC, espengjostol approved these changes

2025-03-06 11:16 UTC, espengjostol commented on .nais/deploy-catbox.yml
> +        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
I dag henter frontend feature-toggles via backend.
Betyr denne endringen at alle frontend-toggles kan hentes direkte fra Unleash?

2025-03-07 12:55 UTC, HalvorHaugan commented on src/pages/VeilederInput/AlertDelB.tsx
> +            <Button size="small" variant="secondary-neutral" onClick={submit}>
Trenger ikke onClick for å submitte, det er native oppførsel (kan ev. sette `type="submit"` for å være eksplisitt).

2025-03-07 12:55 UTC, HalvorHaugan commented on src/pages/VeilederInput/AlertDelB.tsx
> +        action="/pensjon/kalkulator/redirect/detaljert-kalkulator"
Bruke `externalUrls.detaljertKalkulator`?

2025-03-07 12:55 UTC, HalvorHaugan commented on src/pages/VeilederInput/AlertDelB.tsx
> +    <>
Fragment trengs ikke

2025-03-07 12:55 UTC, HalvorHaugan commented on src/pages/VeilederInput/AlertDelB.tsx
> +          <HStack>
Denne HStack-en ser ikke ut til å ha noen effekt. Mente du å bruke en VStack med litt gap kanskje?

2025-03-07 12:55 UTC, HalvorHaugan commented on src/pages/VeilederInput/VeilederInput.tsx
> -  const excludedPaths = findRoutesWithoutLoaders(routes)
Nå er `findRoutesWithoutLoaders` ikke lenger i bruk noe sted og kan fjernes.

2025-03-07 12:55 UTC, HalvorHaugan commented on src/pages/VeilederInput/VeilederInput.tsx
> +          {showDelbWarning && <AlertDelB fnr={veilederBorgerFnr!} />}
Bør vi ha en test for dette? 🤔

2025-03-07 12:55 UTC, HalvorHaugan commented on src/router/__tests__/loaders.test.tsx
> -    it('kaller redirect til /start location når brukeren er veilder', async () => {
Bør vi ikke ha en eller annen test for dette? (Men trenger ikke være på loader-nivå)

2025-03-07 12:55 UTC, HalvorHaugan commented on src/mocks/handlers.ts
Det er også en cypress-mock som kan fjernes

2025-03-12 08:51 UTC, bjorngi commented on .nais/deploy-catbox.yml
> +        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
I teorien så kan det lages endepunkt for det, men trengte unleash for server for å hente redirect toggle, siden den gjøres på BFF siden nå.

2025-03-26 07:46 UTC, bjorngi commented on server/server.ts
> +    })
Nei, copy pasta

2025-03-26 11:25 UTC, bjorngi commented on server/server.ts
> +  // Returner access token fra env-var som det finnes sammen med at man utviklerer lokalt
Fjernet kommentar og logget bruk av ACCESS_TOKEN fra miljøvariabler som error.

2025-04-03 10:31 UTC, bjorngi commented on server/server.ts
Det får komme som en egen ting tenker jeg. Nå skal jo også redirect1963 fases ut, men nå ligger den bare her.

2025-04-04 11:20 UTC, c0d3x approved these changes

2025-04-07 08:23 UTC, HalvorHaugan requested changes

2025-04-07 08:23 UTC, HalvorHaugan commented on vite.config.ts
> +        target: 'http://localhost:8080',
Kommer følgende feilmelding når Cypress kjører:
```
7:38:54 AM [vite] http proxy error: /pensjon/kalkulator/api/feature/utvidet-simuleringsresultat
AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1121:18)
    at afterConnectMultiple (node:net:1688:7)
```
Tipper det skjer pga. denne endringen, kombinert med at det mangler mock for det endepunktet i e2e.ts. Legger du til mock?

2025-04-07 11:01 UTC, HalvorHaugan approved these changes

2025-04-07 20:19 UTC, merged