Mh/pek 92
navikt/pensjonskalkulator-frontend pull request #172
Opened 2023-07-07 07:08 UTC by MarionHauffNAV

2023-08-15 08:02 UTC, espengjostol requested changes

2023-08-15 08:02 UTC, espengjostol commented on src/translations/nb.ts
> +  'error.global.title': 'Oops! Det har oppstått en uventet feil',
Kanskje fjerne "Oops!" (mitt alternative forslag: "Vi beklager, det har oppstått en uventet feil")

2023-08-15 08:09 UTC, espengjostol commented on src/routes/stegvisning/Step1/__tests__/Step1.test.tsx
> +  it('render hilsen uten fornavn når henting av personopplysninger er delvis vellykket (mangler sivilstand)', async () => {
render -> rendrer

2023-08-16 07:45 UTC, MarionHauffNAV commented on src/routes/stegvisning/Step5/Step5Feil.tsx
> +    window.location.href = 'http://www.nav.no/pensjon'
Ja, nå etter merge fikk jeg gjenbruke externalUrls.dinPensjon
Mulig dette skal flyttes under `translations` til slutt, slik at man enklere kan redigere det ved behov.

2023-08-16 07:47 UTC, MarionHauffNAV commented on src/translations/nb.ts
> +  'error.global.title': 'Oops! Det har oppstått en uventet feil',
Resolver samtalen, ref besvarelse i denne PR https://github.com/navikt/pensjonskalkulator-frontend/pull/195

2023-08-16 10:16 UTC, espengjostol approved these changes

2023-08-16 10:16 UTC, merged