legger til 404 feilside
navikt/pensjonskalkulator-frontend pull request #193
Opened 2023-08-04 13:31 UTC by MarionHauffNAV

2023-08-14 13:13 UTC, espengjostol requested changes

2023-08-14 13:13 UTC, espengjostol commented on src/translations/nb.ts
> +  'errorpage.404.button_2': 'Tilbake til Din Pensjon',
Burde ikke knappenavnene ("button_1", "button_2") være mer beskrivende?

2023-08-14 13:13 UTC, espengjostol commented on src/translations/nb.ts
> +  'errorpage.404.title': 'Oops! Siden du leter etter finnes ikke.',
Skal vi virkelig bruke "Oops!"?

2023-08-14 13:13 UTC, espengjostol commented on src/translations/nb.ts
> +    'Hvis du skrev inn adressen direkte i nettleseren kan du sjekke om den er stavet riktig.',
Jeg foreslår en liten justering: "Hvis du skrev inn adressen direkte i nettleseren, vennligst sjekk om den er stavet riktig."

2023-08-14 13:13 UTC, espengjostol commented on src/routes/routes.tsx
> +export const externalsUrls = {
externalsUrls -> externalUrls

2023-08-14 13:13 UTC, espengjostol commented on src/routes/routes.tsx
> +  dinPensjon: 'http://www.nav.no/pensjon',
`http://www.nav.no/pensjon` -> `https://nav.no/pensjon`
(Mest estetikk, siden begge url-er virker, men man ender uansett opp på den siste :)

2023-08-15 07:38 UTC, espengjostol approved these changes

2023-08-15 08:50 UTC, MarionHauffNAV commented on src/translations/nb.ts
> +  'errorpage.404.title': 'Oops! Siden du leter etter finnes ikke.',
Følges opp i egen tråd med Cecilie

2023-08-15 08:50 UTC, MarionHauffNAV commented on src/translations/nb.ts
> +    'Hvis du skrev inn adressen direkte i nettleseren kan du sjekke om den er stavet riktig.',
Følges opp i egen tråd med Cecilie

2023-08-15 08:51 UTC, merged