PEK-107
navikt/pensjonskalkulator-frontend pull request #199
Opened 2023-08-08 08:18 UTC by MarionHauffNAV

- Legger til logikk for å flytte fokus til headings
- Legger til aria-polite og bedre tekster for loading
- Fjerner overflødige alt tekster på illustrasjoner

2023-08-14 12:27 UTC, espengjostol requested changes
En liten grammatikk-detalj :)

2023-08-14 12:27 UTC, espengjostol commented on src/containers/Pensjonsberegning/Pensjonsberegning.tsx
> +        title="Ett øyeblikk, vi henter tidligste mulige uttaksalder"
Ett -> Et

2023-08-14 12:27 UTC, espengjostol commented on src/routes/__tests__/routes.test.tsx
> +          'Ett øyeblikk, vi henter tidligste mulige uttaksalder'
Ett -> Et

2023-08-14 12:27 UTC, espengjostol commented on src/routes/stegvisning/Step3/Step3.tsx
> +            title="Ett øyeblikk, vi henter informasjon om din offentlig tjenestepensjon"
Ett -> Et

2023-08-15 08:42 UTC, MarionHauffNAV commented
@espengjostol til info har jeg oppdatert koden og fjernet ganske mye som ble overflødig:
- fjernet programmatisk fokus flyt i stegvisning (inkl. ref og tabindex) takket være bugfiks som kom fra Aksel i siste versjon
- korrektur på grammatiske feil

2023-08-15 10:02 UTC, espengjostol approved these changes

2023-08-15 10:21 UTC, merged