Mh/pek 98
navikt/pensjonskalkulator-frontend pull request #209
Opened 2023-08-15 05:20 UTC by MarionHauffNAV

- utvider Error Step
- legger til feilmelding på step 3 - når kall til /tpo-medlemskap feiler

(!) Obs, denne Pull Request bygger videre på branch mh/PEK-92
Se denne PR først: https://github.com/navikt/pensjonskalkulator-frontend/pull/172

2023-08-15 08:22 UTC, espengjostol requested changes

2023-08-15 08:22 UTC, espengjostol commented on src/components/Grunnlag/sections/__tests__/Sivilstand.test.tsx
> +  it('viser feilmelding når henting av personoppluysninger er delvis vellykket (mangler sivilstand)', async () => {
personoppluysninger -> personopplysninger

2023-08-15 08:22 UTC, espengjostol commented on src/routes/stegvisning/Step1/__tests__/Step1.test.tsx
> +  it('render hilsen uten fornavn når henting av personopplysninger er delvis vellykket (mangler sivilstand)', async () => {
render -> rendrer

2023-08-15 08:22 UTC, espengjostol commented on src/routes/stegvisning/Step5/Step5Feil.tsx
> +    window.location.href = 'http://www.nav.no/pensjon'
`http://www.nav.no/pensjon` -> `https://nav.no/pensjon`
Kanskje dette burde være en felles konstantverdi?

2023-08-15 08:22 UTC, espengjostol commented on src/translations/nb.ts
> +    'Vi kan dessverre ikke hente inn avtaler om tjenestepensjon fra offentlig sektor. Har du vært eller er ansatt i offentlig sektor, kan du sjekke hos aktuell tjenestepensjonsordning (f.eks. Statens
1. Oslo Pensjonskasse -> Oslo Pensjonsforsikring
2. Fjern ekstra mellomrom i "fra privat"

2023-08-15 08:22 UTC, espengjostol commented on src/translations/nb.ts
> +  'error.global.title': 'Oops! Det har oppstått en uventet feil',
Mitt alternative forslag: "Vi beklager, det har oppstått en uventet feil"

2023-08-15 08:22 UTC, espengjostol commented on src/translations/nb.ts
> +    'Vi jobber med å rette feilen. Hvis problemet vedvarer, kan du kontakte oss på XX XX XX XX.',
XX XX XX XX -> telefonnummer 55 55 33 34

2023-08-16 10:11 UTC, espengjostol approved these changes

2023-08-17 06:56 UTC, MarionHauffNAV commented on src/translations/nb.ts
> +    'Vi kan dessverre ikke hente inn avtaler om tjenestepensjon fra offentlig sektor. Har du vært eller er ansatt i offentlig sektor, kan du sjekke hos aktuell tjenestepensjonsordning (f.eks. Statens
1. sendt videre til Cecilie som ser på det når Øyvind er tilbake
2. rettet

2023-08-17 06:57 UTC, MarionHauffNAV commented on src/translations/nb.ts
> +  'error.global.title': 'Oops! Det har oppstått en uventet feil',
Meldt videre til Cecilie

2023-08-17 08:43 UTC, espengjostol commented on src/translations/nb.ts
>      'Du er eller har vært medlem i en offentlig tjenestepensjonsordning og kan ha rett til tjenestepensjon. Men vi kan dessverre ikke hente inn dine avtaler. Sjekk hva som gjelder deg hos din tjenest
Jeg ser at det ikke er endret i denne PR, men det skal være `Oslo Pensjonsforsikring` (ikke `Oslo Pensjonskasse`).

2023-08-17 08:50 UTC, MarionHauffNAV commented on src/translations/nb.ts
>      'Du er eller har vært medlem i en offentlig tjenestepensjonsordning og kan ha rett til tjenestepensjon. Men vi kan dessverre ikke hente inn dine avtaler. Sjekk hva som gjelder deg hos din tjenest
Ref praten på Slack, resolver jeg denne. Håndteres av Cecilie og Øyvind. :)

2023-08-17 08:51 UTC, merged