Mh/pek 50 kobling til simulering av alderspensjon
navikt/pensjonskalkulator-frontend pull request #225
Opened 2023-08-23 15:14 UTC by MarionHauffNAV

(!) Denne PR bygger på PEK/94 - base branch to be updated before merge

- oppdaterer types og mocks for simulering endepunktet
- kobler frontend (RTK Query og visningen) til simulering endepunktet
- flytting/refaktor av utils

2023-08-24 07:58 UTC, espengjostol requested changes

2023-08-24 07:58 UTC, espengjostol commented on src/components/Pensjonssimulering/Pensjonssimulering.tsx
> +          title="Et øyeblikk, vi simulerer pensjonen din"
Vet ikke om vi skal bruke begrepet "simulerer" for visning til brukeren. Forslag: "beregner".

2023-08-24 07:58 UTC, espengjostol commented on src/state/api/__tests__/apiSlice.test.ts
> +      simuleringstype: 'ALDER_M_AFP_PRIVAT',
Tror denne skal være `ALDERSPENSJON_MED_AFP_PRIVAT `

2023-08-24 07:58 UTC, espengjostol commented on src/state/api/apiSlice.types.ts
> +  simuleringstype: 'ALDER' | 'ALDER_M_AFP_PRIVAT'
Tror denne skal være `'ALDERSPENSJON' | 'ALDERSPENSJON_MED_AFP_PRIVAT'`

2023-08-24 07:58 UTC, espengjostol commented on src/state/api/utils.ts
> +    simuleringstype: afp === 'ja_privat' ? 'ALDER_M_AFP_PRIVAT' : 'ALDER',
Tror denne skal være `'ALDERSPENSJON_MED_AFP_PRIVAT' : 'ALDERSPENSJON'`

2023-08-24 07:58 UTC, espengjostol commented on src/components/Pensjonssimulering/__tests__/Pensjonssimulering-utils.test.ts
> +            belop: 20000,
I responsen er det `beloep` (ikke `belop`)

2023-08-24 09:04 UTC, MarionHauffNAV commented on src/state/api/apiSlice.types.ts
> +  simuleringstype: 'ALDER' | 'ALDER_M_AFP_PRIVAT'
Stemmer. Jeg hentet feil verdi fra eldre mocks. Ser i Swagger nå at det er som du sier. :)

2023-08-24 09:40 UTC, espengjostol approved these changes

2023-08-28 11:52 UTC, MarionHauffNAV commented on src/components/Pensjonssimulering/utils.ts
> +  pensjonsberegninger: Pensjonsberegning[] = []
TODO: Her bør det legges startAlder og sluttAlder, ved f.eks bruk av MAX_UTTAKSALDER slik at array'ene for alderspensjon, afp og tjenestepensjon alltid har lik lengde. Hvis ikke vil Highcharts vise uheldige resultater

2023-09-05 12:56 UTC, bjorngi approved these changes

2023-09-05 13:00 UTC, merged